# redis.conf

# Enable password authentication
requirepass 2~5B5XfGIJH_£5_hC

# Optional: persist data
save 900 1
save 300 10
save 60 10000

# Optional: log level
loglevel notice

# Optional: bind to all interfaces
# bind 0.0.0.0

# Optional: specify how Redis handles memory
maxmemory 256mb
maxmemory-policy allkeys-lru
