// models/Product.js
const { required } = require("joi");
const mongoose = require("mongoose");
const { Schema } = mongoose;

/* -------------------------------------------------------------------------- */
/*                               SUB-SCHEMAS                                  */
/* -------------------------------------------------------------------------- */

// Product variant schema
const VariantSchema = new Schema({
  name: { type: String, required: false, trim: true },
  options: [{ type: String, trim: true }],
});

// Product variation schema
// NOTE: Variations are identified by their attributes + parent product SKU.
// SKU field is now optional; if provided must be unique. If omitted, use attribute combination as key.
const VariationSchema = new Schema({
  attributes: [
    {
      name: String,
      value: Schema.Types.Mixed,
    },
  ],
  sku: {
    type: String,
    unique: true,
    uppercase: true,
    trim: true,
    default: null,
  },
  stockQty: { type: Number, min: 0, default: 0 },
  price: { type: Number, min: 0, required: true },
  images: [
    {
      url: { type: String, trim: true },
      alt: { type: String, trim: true },
      isPrimary: { type: Boolean, default: false },
      sortOrder: { type: Number, default: 0 },
    },
  ],
  weight: {
    value: Number,
    unit: { type: String, enum: ["kg", "g", "lb", "oz"], default: "kg" },
  },
  dimensions: {
    length: Number,
    width: Number,
    height: Number,
    unit: { type: String, enum: ["cm", "in", "m"], default: "cm" },
  },
});

// Review summaries are handled by the ecommerce service; no local review schema required.

// Audit trail schema
const ProductAuditSchema = new Schema({
  action: {
    type: String,
    enum: ["create", "update", "delete", "stock_change"],
    required: true,
  },
  changedBy: { type: String, default: null },
  timestamp: { type: Date, default: Date.now },
  oldValue: Schema.Types.Mixed,
  newValue: Schema.Types.Mixed,
});

// Shop availability schema
// NOTE: Shop availability is simplified — we store a single `shopId` on the product.

/* -------------------------------------------------------------------------- */
/*                               MAIN PRODUCT SCHEMA                          */
/* -------------------------------------------------------------------------- */

const productSchema = new Schema(
  {
    /* ------------------------------ Ownership ------------------------------ */
    companyId: { type: String, required: true, index: true },
    shopId: { type: String, index: true },

    /* ------------------------------ Identifiers ---------------------------- */
    asin: { type: String, unique: true, index: true, sparse: true },
    sku: {
      type: String,
      unique: true,
      uppercase: true,
      index: true,
      sparse: true,
    },
    upc: { type: String, trim: true },

    /* NEW AUTO-GENERATED SCANNING FIELDS */
    barcode: { type: String, unique: true, index: true },  // display value (we set to SKU)
    barcodePayload: { type: String }, // base64 encoded full product JSON (for payload encoded in barcode)
    barcodeUrl: { type: String },                            // autogenerated image url
    qrCode: { type: String },                                // base64 encoded full product JSON (QR payload)
    qrPayload: { type: String }, // duplicate/referenced payload for clarity
    qrCodeUrl: { type: String },                             // autogenerated image url
    scanId: { type: String, unique: true, index: true },     // autogenerated

    /* ------------------------------ Basic Info ----------------------------- */
    name: {
      type: String,
      required: true,
      maxlength: 200,
      minlength: 2,
      trim: true,
    },
    slug: {
      type: String,
      unique: true,
      lowercase: true,
      index: true,
      sparse: true,
    },
    description: {
      short: {
        type: String,
        required: true,
        maxLength: 250,
      },
      long: {
        type: String,
        maxLength: 5000,
      },
    },
    bulletPoints: [{ type: String, trim: true }],

    brand: { type: String, required: true, trim: true, index: true },
    manufacturer: { type: String, trim: true },
    tags: { type: [String], default: [], required: false },

    /* ------------------------------ Supplier ------------------------------ */
    supplierName: { type: String, trim: true, default: null },

    /* ------------------------------ Categories ----------------------------- */
    category: {
      type: Schema.Types.ObjectId,
      ref: "Category",
      required: true,
      index: true,
    },
    // Store the level-2 category (parent of selected level-3 category) to help
    // determine which rich fields/specs to show in product forms.
    categoryL2: {
      type: Schema.Types.ObjectId,
      ref: 'Category',
      default: null,
      index: true,
    },

    /* ------------------------------ Pricing ------------------------------- */
    pricing: {
      basePrice: {
        type: Number,
        required: true,
        min: 0,
      },
      salePrice: { type: Number, min: 0 },
      listPrice: { type: Number, min: 0 },
      cost: { type: Number, min: 0 },
      currency: {
        type: String,
        default: "USD",
        enum: ["USD", "EUR", "GBP", "FRW" , "KES"],
      },
    },

    /* ------------------------------ Inventory ------------------------------ */
    inventory: {
      trackQuantity: { type: Boolean, default: true },
      quantity: { type: Number, default: 0, min: 0 },
      lowStockThreshold: { type: Number, default: 10, min: 0 },
      allowBackorder: { type: Boolean, default: false },
    },

    /* ------------------------------ Shop ------------------------------- */
    // Keep only a single shop identifier `shopId` (array of shop availability removed)

    /* ------------------------------ Condition ------------------------------ */
    condition: {
      type: String,
      enum: ["new", "used", "refurbished"],
      default: "new",
    },

    availability: {
      type: String,
      enum: ["in_stock", "out_of_stock", "limited", "scheduled"],
      default: "in_stock",
    },
    scheduledAvailabilityDate: { type: Date, default: null },

    /* ------------------------------ Variants & Variations ------------------------------- */
    // Both variants (option groups) and variations (concrete SKUs with attributes) are now optional.
    // Allows products to be simple (no variants/variations) or complex (multi-variant).
    variants: { type: [VariantSchema], default: [] },
    variations: { type: [VariationSchema], default: [] },

    /* ------------------------------ Attributes ----------------------------- */
    attributes: [
      {
        name: String,
        value: Schema.Types.Mixed,
      },

    ],

    /* ------------------------------ Structured Specs ---------------------- */
    // Flexible key/value specs used to store category-specific fields (e.g. size, color, model)
    specs: [
      {
        name: { type: String, required: true },
        value: Schema.Types.Mixed,
      }
    ],

    /* ------------------------------ Media --------------------------------- */
    images: [
      {
        url: { type: String, required: true, trim: true },
        alt: { type: String, trim: true },
        isPrimary: { type: Boolean, default: false },
        sortOrder: { type: Number, default: 0 },
      },
    ],
    videoUrls: [{ type: String, trim: true }],

    /* ------------------------------ Status / SEO --------------------------- */
    status: {
      type: String,
      enum: ["draft", "active", "inactive", "discontinued"],
      default: "draft",
      index: true,
    },
    visibility: {
      type: String,
      enum: ["public", "private", "hidden"],
      default: "public",
      index: true,
    },
    featured: { type: Boolean, default: false, index: true },
    isActive: { type: Boolean, default: true, index: true },
    sortOrder: { type: Number, default: 0 },

    seo: {
      metaTitle: { type: String, maxLength: 60 },
      metaDescription: { type: String, maxLength: 160 },
      keywords: [String],
    },

    /* ------------------------------ Reviews / Sales ------------------------ */
    // Reviews are managed in the ecommerce-service; keep only sales metrics here
    sales: {
      totalSold: { type: Number, default: 0, min: 0 },
      revenue: { type: Number, default: 0, min: 0 },
      salesRank: { type: Number, default: 0, min: 0 },
    },

    /* ------------------------------ Misc ---------------------------------- */
    browseNodeId: { type: String, trim: true },

    /* ------------------------------ Audit Trail ---------------------------- */
    auditTrail: [ProductAuditSchema],
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/* -------------------------------------------------------------------------- */
/*                             VIRTUALS & METHODS                             */
/* -------------------------------------------------------------------------- */

productSchema.virtual("effectivePrice").get(function () {
  return this.pricing.salePrice || this.pricing.basePrice;
});

// Total stock aggregates variation stockQty when variations exist.
productSchema.virtual("totalStock").get(function () {
  if (this.variations && this.variations.length) {
    return this.variations.reduce((sum, v) => sum + (v.stockQty || 0), 0);
  }
  return this.inventory && typeof this.inventory.quantity === 'number'
    ? this.inventory.quantity
    : 0;
});

productSchema.virtual("stockStatus").get(function () {
  if (!this.inventory.trackQuantity) return "in-stock";
  if (this.inventory.quantity <= 0) {
    return this.inventory.allowBackorder ? "backorder" : "out-of-stock";
  }
  if (this.inventory.quantity <= this.inventory.lowStockThreshold) {
    return "low-stock";
  }
  return "in-stock";
});

/* -------------------------------------------------------------------------- */
/*                          ATTRIBUTE MERGE HELPERS                            */
/* -------------------------------------------------------------------------- */

/**
 * Return merged attributes for a variation sku.
 * Product attributes provide defaults/templates; variation attributes override them.
 * @param {String} sku
 * @returns {Object} flat map of attribute name -> value
 */
productSchema.methods.getEffectiveAttributesForSku = function (sku) {
  const productAttrs = (this.attributes || []).reduce((m, a) => {
    if (a && a.name) m[a.name] = a.value;
    return m;
  }, {});

  if (!sku) return productAttrs;

  const variation = (this.variations || []).find(v => v.sku === sku);
  if (!variation) return productAttrs;

  const variationAttrs = (variation.attributes || []).reduce((m, a) => {
    if (a && a.name) m[a.name] = a.value;
    return m;
  }, {});

  return Object.assign({}, productAttrs, variationAttrs);
};


/* -------------------------------------------------------------------------- */
/*                                   MIDDLEWARE                               */
/* -------------------------------------------------------------------------- */

// Auto-generate slug
productSchema.pre("save", function (next) {
  if (this.isModified("name")) {
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-zA-Z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }
  next();
});

// Auto-generate scanning fields
// Auto-generate scanning & identifier fields (async to ensure uniqueness)
productSchema.pre("save", async function (next) {
  try {
    const Product = this.constructor;

    // Helper to check uniqueness with limited attempts
    const ensureUnique = async (field, genFn, maxAttempts = 5) => {
      let attempts = 0;
      let candidate;
      while (attempts < maxAttempts) {
        candidate = genFn();
        // eslint-disable-next-line no-await-in-loop
        const exists = await Product.findOne({ [field]: candidate }).lean();
        if (!exists) return candidate;
        attempts += 1;
      }
      // If we couldn't find a unique candidate after attempts, return last candidate
      return candidate;
    };

    // SKU - try to create a readable SKU using companyId/slug + random suffix
    if (!this.sku) {
      this.sku = await ensureUnique('sku', () => {
        const prefix = (this.companyId || 'CMP').toString().replace(/[^A-Za-z0-9]/g, '').toUpperCase().slice(0, 4) || 'CMP';
        const base = (this.slug || this.name || '').toString().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 8) || Date.now().toString().slice(-6);
        const suffix = Math.random().toString(36).substring(2, 6).toUpperCase();
        return `${prefix}-${base}-${suffix}`.slice(0, 64);
      });
    }

    // barcode: display value should be SKU. Use SKU when available, otherwise generate one.
    if (!this.barcode) {
      // prefer SKU (which is unique) for human-readable barcode display
      this.barcode = this.sku || await ensureUnique('barcode', () => `BC${Date.now()}${Math.floor(Math.random() * 9999)}`);
    }

    // Create full product payload and encode as base64 for embedding into QR / barcode payloads.
    try {
      // toObject gives a plain object representation; exclude mongoose internals
      const obj = this.toObject ? this.toObject({ depopulate: true, virtuals: false }) : Object.assign({}, this);
      // It's safe to remove mongoose __v if present
      if (obj.__v !== undefined) delete obj.__v;
      const encoded = Buffer.from(JSON.stringify(obj)).toString("base64");

      // QR code should contain the full product data encoded
      this.qrCode = encoded;
      this.qrPayload = encoded;

      // Barcode should display SKU but carry the full encoded payload in barcodePayload
      this.barcodePayload = encoded;
    } catch (e) {
      // If encoding fails for any reason, fallback to lightweight codes
      if (!this.qrCode) this.qrCode = `QR${Date.now()}${Math.floor(Math.random() * 9999)}`;
      if (!this.qrPayload) this.qrPayload = this.qrCode;
    }

    // scanId
    if (!this.scanId) {
      this.scanId = await ensureUnique('scanId', () => `SCAN-${Math.random().toString(36).substring(2, 10).toUpperCase()}`);
    }

    // ASIN - auto-generate if missing. Use a compact alphanumeric pattern.
    if (!this.asin) {
      this.asin = await ensureUnique('asin', () => {
        const hash = Math.random().toString(36).substring(2, 8).toUpperCase();
        return `ASIN${Date.now().toString().slice(-6)}${hash}`;
      });
    }

    // UPC - 12 digit numeric code (generate random; uniqueness checked)
    if (!this.upc) {
      this.upc = await ensureUnique('upc', () => {
        const num = Math.floor(Math.random() * 1e12).toString().padStart(12, '0');
        return num;
      });
    }

    // browseNodeId - low-collision identifier used for browsing trees
    if (!this.browseNodeId) {
      this.browseNodeId = `BN${Date.now().toString().slice(-8)}${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
    }

    return next();
  } catch (err) {
    return next(err);
  }
});

// Update availability if scheduled
productSchema.pre("save", function (next) {
  this.updatedAt = new Date();

  if (
    this.scheduledAvailabilityDate &&
    new Date() < this.scheduledAvailabilityDate
  ) {
    this.availability = "scheduled";
  } else if (
    this.scheduledAvailabilityDate &&
    new Date() >= this.scheduledAvailabilityDate
  ) {
    this.availability = "in_stock";
  }

  next();
});

// Validate category hierarchy
productSchema.pre("save", async function (next) {
  // Ensure assigned category exists and is a level 3 category.
  if (this.isModified("category")) {
    const Category = mongoose.model("Category");
    const category = await Category.findById(this.category);
    if (!category || category.level !== 3) {
      return next(new Error("Invalid category selection: category must be level 3"));
    }

    // If the category is scoped to a company, ensure product.companyId matches
    if (category.companyId && this.companyId && category.companyId !== this.companyId) {
      return next(new Error("Category companyId does not match product companyId"));
    }
  }
  next();
});

/* -------------------------------------------------------------------------- */
/*                                   INDEXES                                  */
/* -------------------------------------------------------------------------- */

productSchema.index({
  companyId: 1,
  category: 1,
});
productSchema.index({
  name: "text",
  "description.short": "text",
  "description.long": "text",
});
// Index variations.sku for fast variation lookup by sku/barcode
productSchema.index({ 'variations.sku': 1 });
productSchema.index({ "pricing.basePrice": 1 });
productSchema.index({ "inventory.quantity": 1 });
productSchema.index({ status: 1, visibility: 1 });
productSchema.index({ brand: 1, status: 1 });
productSchema.index({ featured: 1, sortOrder: 1 });
productSchema.index({ createdAt: -1 });
productSchema.index({ scheduledAvailabilityDate: 1 });
productSchema.index({ companyId: 1, shopId: 1 });
productSchema.index({ shopId: 1, status: 1 });

/* -------------------------------------------------------------------------- */
/*                              EXPORT MODEL                                  */
/* -------------------------------------------------------------------------- */

module.exports = mongoose.model("Product", productSchema);
