// models/Product.js
const mongoose = require("mongoose");
const { Schema } = mongoose;

/* -------------------------------------------------------------------------- */
/*                               SUB-SCHEMAS                                  */
/* -------------------------------------------------------------------------- */

// Product variant schema
const VariantSchema = new Schema({
  name: { type: String, required: true, trim: true },
  options: [{ type: String, trim: true }],
});

// Product variation schema
const VariationSchema = new Schema({
  attributes: [
    {
      name: String,
      value: Schema.Types.Mixed,
    },
  ],
  sku: {
    type: String,
    unique: true,
    required: true,
    trim: true,
    uppercase: true,
  },
  stockQty: { type: Number, min: 0, default: 0 },
  price: { type: Number, min: 0, required: true },
  images: [
    {
      url: { type: String, trim: true },
      alt: { type: String, trim: true },
      isPrimary: { type: Boolean, default: false },
      sortOrder: { type: Number, default: 0 },
    },
  ],
  weight: {
    value: Number,
    unit: { type: String, enum: ["kg", "g", "lb", "oz"], default: "kg" },
  },
  dimensions: {
    length: Number,
    width: Number,
    height: Number,
    unit: { type: String, enum: ["cm", "in", "m"], default: "cm" },
  },
});

// Review summary schema
const ReviewSummarySchema = new Schema({
  averageRating: { type: Number, min: 0, max: 5, default: 0 },
  reviewCount: { type: Number, default: 0 },
  ratingsDistribution: {
    1: { type: Number, default: 0 },
    2: { type: Number, default: 0 },
    3: { type: Number, default: 0 },
    4: { type: Number, default: 0 },
    5: { type: Number, default: 0 },
  },
});

// Audit trail schema
const ProductAuditSchema = new Schema({
  action: {
    type: String,
    enum: ["create", "update", "delete", "stock_change"],
    required: true,
  },
  changedBy: { type: String, default: null },
  timestamp: { type: Date, default: Date.now },
  oldValue: Schema.Types.Mixed,
  newValue: Schema.Types.Mixed,
});

// Shop availability schema
const ShopAvailabilitySchema = new Schema({
  shopId: { type: String, required: true, index: true },
  enabled: { type: Boolean, default: true },
  displayOrder: { type: Number, default: 0 },
  customPrice: {
    type: Number,
    default: null,
    min: 0,
  },
  addedAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

/* -------------------------------------------------------------------------- */
/*                               MAIN PRODUCT SCHEMA                          */
/* -------------------------------------------------------------------------- */

const productSchema = new Schema(
  {
    /* ------------------------------ Ownership ------------------------------ */
    companyId: { type: String, required: true, index: true },
    shopId: { type: String, index: true },

    /* ------------------------------ Identifiers ---------------------------- */
    asin: { type: String, required: true, unique: true, index: true },
    sku: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      index: true,
    },
    upc: { type: String, trim: true },

    /* NEW AUTO-GENERATED SCANNING FIELDS */
    barcode: { type: String, unique: true, index: true },  // autogenerated
    qrCode: { type: String },                                // autogenerated
    scanId: { type: String, unique: true, index: true },     // autogenerated

    /* ------------------------------ Basic Info ----------------------------- */
    name: {
      type: String,
      required: true,
      maxlength: 200,
      minlength: 2,
      trim: true,
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      index: true,
    },
    description: {
      short: {
        type: String,
        required: true,
        maxLength: 250,
      },
      long: {
        type: String,
        maxLength: 5000,
      },
    },
    bulletPoints: [{ type: String, trim: true }],

    brand: { type: String, required: true, trim: true, index: true },
    manufacturer: { type: String, trim: true },
    tags: [String],

    /* ------------------------------ Categories ----------------------------- */
    category: {
      type: Schema.Types.ObjectId,
      ref: "Category",
      required: true,
      index: true,
    },
    subcategory: { type: Schema.Types.ObjectId, ref: "Category", index: true },
    subSubcategory: {
      type: Schema.Types.ObjectId,
      ref: "Category",
      index: true,
    },

    /* ------------------------------ Pricing ------------------------------- */
    pricing: {
      basePrice: {
        type: Number,
        required: true,
        min: 0,
      },
      salePrice: { type: Number, min: 0 },
      listPrice: { type: Number, min: 0 },
      cost: { type: Number, min: 0 },
      currency: {
        type: String,
        default: "USD",
        enum: ["USD", "EUR", "GBP", "FRW"],
      },
    },

    /* ------------------------------ Inventory ------------------------------ */
    inventory: {
      trackQuantity: { type: Boolean, default: true },
      quantity: { type: Number, default: 0, min: 0 },
      lowStockThreshold: { type: Number, default: 10, min: 0 },
      allowBackorder: { type: Boolean, default: false },
    },

    /* ------------------------------ Shop Availability ---------------------- */
    shopAvailability: [ShopAvailabilitySchema],

    /* ------------------------------ Condition ------------------------------ */
    condition: {
      type: String,
      enum: ["new", "used", "refurbished"],
      default: "new",
    },

    availability: {
      type: String,
      enum: ["in_stock", "out_of_stock", "limited", "scheduled"],
      default: "in_stock",
    },
    scheduledAvailabilityDate: { type: Date, default: null },

    /* ------------------------------ Variants ------------------------------- */
    variants: [VariantSchema],
    variations: [VariationSchema],

    /* ------------------------------ Attributes ----------------------------- */
    attributes: [
      {
        name: String,
        value: Schema.Types.Mixed,
      },
    ],

    /* ------------------------------ Media --------------------------------- */
    images: [
      {
        url: { type: String, required: true, trim: true },
        alt: { type: String, trim: true },
        isPrimary: { type: Boolean, default: false },
        sortOrder: { type: Number, default: 0 },
      },
    ],
    videoUrls: [{ type: String, trim: true }],

    /* ------------------------------ Status / SEO --------------------------- */
    status: {
      type: String,
      enum: ["draft", "active", "inactive", "discontinued"],
      default: "draft",
      index: true,
    },
    visibility: {
      type: String,
      enum: ["public", "private", "hidden"],
      default: "public",
      index: true,
    },
    featured: { type: Boolean, default: false, index: true },
    isActive: { type: Boolean, default: true, index: true },
    sortOrder: { type: Number, default: 0 },

    seo: {
      metaTitle: { type: String, maxLength: 60 },
      metaDescription: { type: String, maxLength: 160 },
      keywords: [String],
    },

    /* ------------------------------ Reviews / Sales ------------------------ */
    reviewSummary: ReviewSummarySchema,
    sales: {
      totalSold: { type: Number, default: 0, min: 0 },
      revenue: { type: Number, default: 0, min: 0 },
      salesRank: { type: Number, default: 0, min: 0 },
    },

    /* ------------------------------ Misc ---------------------------------- */
    browseNodeId: { type: String, trim: true },

    /* ------------------------------ Audit Trail ---------------------------- */
    auditTrail: [ProductAuditSchema],
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/* -------------------------------------------------------------------------- */
/*                             VIRTUALS & METHODS                             */
/* -------------------------------------------------------------------------- */

productSchema.virtual("effectivePrice").get(function () {
  return this.pricing.salePrice || this.pricing.basePrice;
});

productSchema.virtual("stockStatus").get(function () {
  if (!this.inventory.trackQuantity) return "in-stock";
  if (this.inventory.quantity <= 0) {
    return this.inventory.allowBackorder ? "backorder" : "out-of-stock";
  }
  if (this.inventory.quantity <= this.inventory.lowStockThreshold) {
    return "low-stock";
  }
  return "in-stock";
});

/* -------------------------------------------------------------------------- */
/*                                   MIDDLEWARE                               */
/* -------------------------------------------------------------------------- */

// Auto-generate slug
productSchema.pre("save", function (next) {
  if (this.isModified("name")) {
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-zA-Z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }
  next();
});

// Auto-generate scanning fields
productSchema.pre("save", function (next) {
  if (!this.barcode) {
    this.barcode = `BC${Date.now()}${Math.floor(Math.random() * 9999)}`;
  }

  if (!this.qrCode) {
    this.qrCode = `QR${Date.now()}${Math.floor(Math.random() * 9999)}`;
  }

  if (!this.scanId) {
    this.scanId = `SCAN-${Math.random().toString(36).substring(2, 10).toUpperCase()}`;
  }

  next();
});

// Update availability if scheduled
productSchema.pre("save", function (next) {
  this.updatedAt = new Date();

  if (
    this.scheduledAvailabilityDate &&
    new Date() < this.scheduledAvailabilityDate
  ) {
    this.availability = "scheduled";
  } else if (
    this.scheduledAvailabilityDate &&
    new Date() >= this.scheduledAvailabilityDate
  ) {
    this.availability = "in_stock";
  }

  next();
});

// Validate category hierarchy
productSchema.pre("save", async function (next) {
  if (
    this.isModified("category") ||
    this.isModified("subcategory") ||
    this.isModified("subSubcategory")
  ) {
    const Category = mongoose.model("Category");

    const category = await Category.findById(this.category);
    if (!category || category.level !== 1) {
      return next(new Error("Invalid category selection"));
    }

    if (this.subcategory) {
      const subcategory = await Category.findById(this.subcategory);
      if (
        !subcategory ||
        subcategory.level !== 3 ||
        !subcategory.parentCategory.equals(this.category)
      ) {
        return next(new Error("Invalid subcategory selection"));
      }

      if (this.subSubcategory) {
        const subSubcategory = await Category.findById(this.subSubcategory);
        if (
          !subSubcategory ||
          subSubcategory.level !== 3 ||
          !subSubcategory.parentCategory.equals(this.subcategory)
        ) {
          return next(new Error("Invalid sub-subcategory selection"));
        }
      }
    }
  }
  next();
});

/* -------------------------------------------------------------------------- */
/*                                   INDEXES                                  */
/* -------------------------------------------------------------------------- */

productSchema.index({
  companyId: 1,
  category: 1,
  subcategory: 1,
  subSubcategory: 1,
});
productSchema.index({
  name: "text",
  "description.short": "text",
  "description.long": "text",
});
productSchema.index({ "pricing.basePrice": 1 });
productSchema.index({ "inventory.quantity": 1 });
productSchema.index({ status: 1, visibility: 1 });
productSchema.index({ brand: 1, status: 1 });
productSchema.index({ featured: 1, sortOrder: 1 });
productSchema.index({ "reviewSummary.averageRating": -1 });
productSchema.index({ createdAt: -1 });
productSchema.index({ scheduledAvailabilityDate: 1 });
productSchema.index({ companyId: 1, "shopAvailability.shopId": 1 });
productSchema.index({ "shopAvailability.shopId": 1, status: 1 });

/* -------------------------------------------------------------------------- */
/*                              EXPORT MODEL                                  */
/* -------------------------------------------------------------------------- */

module.exports = mongoose.model("Product", productSchema);
